CC=gcc --std=gnu99 -g

all: movies_by_year

movies_by_year: movies_by_year.c movies_by_year.h
	$(CC) movies_by_year.c -o movies_by_year

clean:
	rm -rf movies_by_year.o movies_by_year movies_by_year.dSYM