CC=gcc --std=gnu99 -g -pthread -lm

all: line_processor

line_processor: line_processor.c 
	$(CC) line_processor.c -o line_processor

clean:
	rm -rf line_processor.o line_processor f line_processor.dSYM